"""Generated by tools/export_static.py — do not edit.

The grading module from the PyForge backend, shipped verbatim so that the
browser grades submissions with the same code the server would. Only its
application imports are replaced, by the shims below.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum


class _NullLogger:
    """grading.py logs author mistakes; in a browser there is nowhere to log."""

    def warning(self, *args: object, **kwargs: object) -> None:
        pass

    def info(self, *args: object, **kwargs: object) -> None:
        pass


def get_logger(_name: str) -> _NullLogger:
    return _NullLogger()


class GraderKind(StrEnum):
    STDOUT_MATCH = "stdout_match"
    PYTEST = "pytest"
    STATIC_ASSERT = "static_assert"
    MULTIPLE_CHOICE = "multiple_choice"


class SubmissionStatus(StrEnum):
    PASSED = "passed"
    FAILED = "failed"
    PARTIAL = "partial"
    ERROR = "error"
    TIMED_OUT = "timed_out"


@dataclass(frozen=True)
class ExecutionResult:
    """The subset of the server's ExecutionResult that grading reads."""

    ok: bool = False
    exit_code: int = 1
    stdout: str = ""
    stderr: str = ""
    timed_out: bool = False
    duration_ms: int = 0
    error: str | None = None


class Exercise:
    """A stand-in for the ORM row.

    ``grading.py`` only reads attributes off it, and every annotation in that
    module is a string (``from __future__ import annotations``), so nothing ever
    checks this type.
    """

    def __init__(self, data: dict) -> None:
        self.slug = data.get("slug", "")
        self.grader = data.get("grader", "")
        self.grader_config = data.get("grader_config") or {}
        self.misconception_rules = data.get("misconception_rules") or []


"""Grading: turning submitted code into a score, checks and feedback.

Four deterministic graders cover the exercise catalogue:

``stdout_match``     compare program output against an expected string
``pytest``           run a hidden test suite; score = passed / total
``static_assert``    assert structural facts about the source (uses AST, not regex)
``multiple_choice``  concept checks

A grader returns a :class:`GradeResult`: a score in [0, 1], a list of per-check
outcomes the UI renders as a checklist, learner-facing feedback, and any
misconceptions the evidence implies. Nothing here talks to HTTP or to the
mastery engine — the submission service composes them.
"""


import ast
import difflib
import re
from dataclasses import dataclass, field
from typing import Any


logger = get_logger(__name__)

#: pytest's short summary line, e.g. "3 passed, 1 failed in 0.12s".
_PYTEST_TALLY = re.compile(r"(\d+)\s+(passed|failed|error|errors|skipped|xfailed|xpassed)")
#: Lines emitted per test in verbose mode: "tests/test_x.py::test_name PASSED".
_PYTEST_CASE = re.compile(r"^(?P<node>\S+::\S+)\s+(?P<outcome>PASSED|FAILED|ERROR|SKIPPED)")


@dataclass(slots=True)
class Check:
    """One assessable criterion within a submission."""

    name: str
    passed: bool
    message: str = ""
    expected: str | None = None
    actual: str | None = None
    diff: str | None = None

    def to_dict(self) -> dict[str, Any]:
        """Serialise for storage and the API."""
        return {
            "name": self.name,
            "passed": self.passed,
            "message": self.message,
            "expected": self.expected,
            "actual": self.actual,
            "diff": self.diff,
        }


@dataclass(slots=True)
class GradeResult:
    """The verdict on a submission."""

    score: float
    status: SubmissionStatus
    checks: list[Check] = field(default_factory=list)
    feedback: str = ""
    misconceptions: list[str] = field(default_factory=list)

    @property
    def passed(self) -> bool:
        """Whether every check succeeded."""
        return self.status is SubmissionStatus.PASSED


# ---------------------------------------------------------------------------
# Output normalisation
# ---------------------------------------------------------------------------


def normalise_output(text: str, *, strip_trailing: bool = True, ignore_case: bool = False) -> str:
    """Normalise program output before comparison.

    Trailing whitespace on each line and a missing final newline are not
    interesting differences for a learner; a missing word is. Everything else
    is preserved so that spacing bugs are still caught.
    """
    lines = [line.rstrip() for line in text.replace("\r\n", "\n").split("\n")]
    if strip_trailing:
        while lines and not lines[-1]:
            lines.pop()
    joined = "\n".join(lines)
    return joined.lower() if ignore_case else joined


def build_diff(expected: str, actual: str) -> str:
    """Unified diff of expected vs actual output, ready to render."""
    return "\n".join(
        difflib.unified_diff(
            expected.split("\n"),
            actual.split("\n"),
            fromfile="expected",
            tofile="your output",
            lineterm="",
        )
    )


# ---------------------------------------------------------------------------
# Runtime-error interpretation
# ---------------------------------------------------------------------------

_ERROR_GUIDANCE: dict[str, tuple[str, str]] = {
    "SyntaxError": (
        "syntax-error",
        "Python could not parse your file. Check for a missing colon, an unclosed "
        "bracket or a stray quote — the reported line is often just *after* the mistake.",
    ),
    "IndentationError": (
        "indentation",
        "Python uses indentation to define blocks. Make every line in a block line up, "
        "and never mix tabs with spaces.",
    ),
    "NameError": (
        "undefined-name",
        "You used a name Python has never seen. Check the spelling, and make sure the "
        "assignment happens before the use.",
    ),
    "TypeError": (
        "type-mismatch",
        "An operation received the wrong type — often a str where an int was needed. "
        "`input()` always returns a str; convert it with `int()` first.",
    ),
    "ValueError": (
        "value-conversion",
        "The type was right but the value was not convertible or acceptable, e.g. `int('twelve')`.",
    ),
    "IndexError": (
        "off-by-one",
        "You indexed past the end of a sequence. Valid indexes run from 0 to len(seq) - 1.",
    ),
    "KeyError": (
        "missing-key",
        "That key is not in the dictionary. Use `d.get(key, default)` when a key may be absent.",
    ),
    "AttributeError": (
        "wrong-attribute",
        "That object has no such attribute or method. Check the object's actual type — "
        "this often means a function returned None.",
    ),
    "ZeroDivisionError": (
        "unguarded-division",
        "Division by zero. Guard the denominator before dividing.",
    ),
    "ModuleNotFoundError": (
        "missing-import",
        "That module is not available in the sandbox. Only the standard library and pytest "
        "are installed.",
    ),
    "RecursionError": (
        "runaway-recursion",
        "Your recursion never reached a base case. Every recursive function needs a "
        "condition that stops it.",
    ),
}


def interpret_traceback(stderr: str) -> tuple[str | None, str]:
    """Extract the exception type from a traceback and explain it.

    Returns ``(misconception_slug, explanation)``. Both are empty/None when the
    text does not look like a Python traceback.
    """
    if not stderr.strip():
        return None, ""
    match = re.search(r"^(\w+(?:Error|Exception|Warning))\b:?(.*)$", stderr, re.MULTILINE)
    if not match:
        return None, ""
    exception_type = match.group(1)
    detail = match.group(2).strip()
    slug, guidance = _ERROR_GUIDANCE.get(
        exception_type,
        (
            "runtime-error",
            "Read the last line of the traceback first: it names the error type and the reason.",
        ),
    )
    headline = f"**{exception_type}**" + (f": {detail}" if detail else "")
    return slug, f"{headline}\n\n{guidance}"


# ---------------------------------------------------------------------------
# Graders
# ---------------------------------------------------------------------------


def grade_stdout_match(exercise: Exercise, result: ExecutionResult) -> GradeResult:
    """Compare program output with the expected text."""
    config = exercise.grader_config
    expected_raw = str(config.get("expected_stdout", ""))
    ignore_case = bool(config.get("ignore_case", False))

    if result.timed_out:
        return _timeout_result()
    if result.exit_code != 0:
        return _crash_result(result)

    expected = normalise_output(expected_raw, ignore_case=ignore_case)
    actual = normalise_output(result.stdout, ignore_case=ignore_case)
    passed = expected == actual

    check = Check(
        name="Program output matches the expected output",
        passed=passed,
        message="Output matched exactly." if passed else "Output did not match.",
        expected=expected_raw,
        actual=result.stdout,
        diff=None if passed else build_diff(expected, actual),
    )
    feedback = (
        "Your program produced exactly the expected output."
        if passed
        else "The program ran, but the output differs. Compare the diff line by line — "
        "watch for spelling, spacing and missing newlines."
    )
    return GradeResult(
        score=1.0 if passed else 0.0,
        status=SubmissionStatus.PASSED if passed else SubmissionStatus.FAILED,
        checks=[check],
        feedback=feedback,
        misconceptions=[] if passed else ["output-mismatch"],
    )


def grade_pytest(exercise: Exercise, result: ExecutionResult) -> GradeResult:
    """Score a hidden pytest suite as ``passed / total``."""
    if result.timed_out:
        return _timeout_result()

    combined = f"{result.stdout}\n{result.stderr}"
    cases = [
        Check(
            name=match.group("node")
            .split("::")[-1]
            .replace("_", " ")
            .removeprefix("test ")
            .strip(),
            passed=match.group("outcome") == "PASSED",
            message=match.group("outcome").title(),
        )
        for match in (_PYTEST_CASE.match(line) for line in combined.splitlines())
        if match
    ]

    tallies = {kind: int(count) for count, kind in _PYTEST_TALLY.findall(combined)}
    passed_count = tallies.get("passed", sum(1 for c in cases if c.passed))
    failed_count = (
        tallies.get("failed", 0) + tallies.get("error", 0) + tallies.get("errors", 0)
    ) or sum(1 for c in cases if not c.passed)
    total = passed_count + failed_count

    if total == 0:
        # Collection error: the suite never ran. That is a hard failure, and the
        # traceback is the most useful thing we can show.
        slug, explanation = interpret_traceback(combined)
        return GradeResult(
            score=0.0,
            status=SubmissionStatus.ERROR,
            checks=[
                Check(
                    name="Test suite collection",
                    passed=False,
                    message="pytest could not run your code.",
                    actual=combined.strip()[:4000],
                )
            ],
            feedback=explanation
            or "pytest could not collect any tests. Check that your file parses and that "
            "required functions exist with the exact names in the brief.",
            misconceptions=[slug] if slug else ["collection-error"],
        )

    if not cases:
        cases = [
            Check(
                name=f"{passed_count} of {total} tests",
                passed=failed_count == 0,
                message=combined.strip()[-1500:],
            )
        ]

    score = passed_count / total
    if score >= 0.999:
        status = SubmissionStatus.PASSED
        feedback = f"All {total} tests passed."
    elif score > 0:
        status = SubmissionStatus.PARTIAL
        feedback = (
            f"{passed_count} of {total} tests passed. Read the first failure only — "
            "later failures are often knock-on effects of the same bug."
        )
    else:
        status = SubmissionStatus.FAILED
        feedback = "No tests passed yet. Start with the first failing assertion."

    misconceptions: list[str] = []
    if failed_count:
        slug, explanation = interpret_traceback(combined)
        if slug:
            misconceptions.append(slug)
            feedback = f"{feedback}\n\n{explanation}"
        misconceptions.extend(_match_authored_misconceptions(exercise, combined))

    return GradeResult(
        score=round(score, 4),
        status=status,
        checks=cases,
        feedback=feedback,
        misconceptions=sorted(set(misconceptions)),
    )


def grade_static_assert(exercise: Exercise, files: dict[str, str]) -> GradeResult:
    """Assert structural properties of the source using the AST.

    Configuration::

        {
          "target_file": "main.py",
          "assertions": [
            {"kind": "defines_function", "name": "total", "label": "Defines total()"},
            {"kind": "uses_construct",   "node": "ListComp"},
            {"kind": "forbids_construct","node": "For", "message": "Use a comprehension"},
            {"kind": "max_lines",        "value": 12},
            {"kind": "has_docstring",    "name": "total"},
            {"kind": "has_type_hints",   "name": "total"}
          ]
        }

    Structural checks use the AST rather than string search so that a construct
    inside a comment or a string literal never counts as a use.
    """
    config = exercise.grader_config
    target = str(config.get("target_file", "main.py"))
    source = files.get(target, "")
    assertions: list[dict[str, Any]] = list(config.get("assertions", []))

    if not source.strip():
        return GradeResult(
            score=0.0,
            status=SubmissionStatus.FAILED,
            checks=[
                Check(name=f"{target} contains code", passed=False, message=f"{target} is empty.")
            ],
            feedback=f"Write your solution in `{target}`.",
            misconceptions=["empty-submission"],
        )

    try:
        tree = ast.parse(source)
    except SyntaxError as exc:
        return GradeResult(
            score=0.0,
            status=SubmissionStatus.ERROR,
            checks=[
                Check(name="Code parses", passed=False, message=f"Line {exc.lineno}: {exc.msg}")
            ],
            feedback=f"**SyntaxError** on line {exc.lineno}: {exc.msg}\n\n"
            "Python stopped before running anything. Fix the syntax first.",
            misconceptions=["syntax-error"],
        )

    checks = [_evaluate_assertion(tree, source, spec) for spec in assertions]
    if not checks:
        checks = [Check(name="Code parses", passed=True, message="No assertions configured.")]

    passed_count = sum(1 for check in checks if check.passed)
    score = passed_count / len(checks)
    status = (
        SubmissionStatus.PASSED
        if score >= 0.999
        else SubmissionStatus.PARTIAL
        if score > 0
        else SubmissionStatus.FAILED
    )
    failures = [check.name for check in checks if not check.passed]
    feedback = (
        "Your solution meets every structural requirement."
        if not failures
        else "Not there yet: " + "; ".join(failures[:3])
    )
    return GradeResult(
        score=round(score, 4),
        status=status,
        checks=checks,
        feedback=feedback,
        misconceptions=[] if not failures else ["structural-requirement"],
    )


def grade_multiple_choice(exercise: Exercise, selected_index: int) -> GradeResult:
    """Score a concept check."""
    config = exercise.grader_config
    correct = int(config.get("correct_index", 0))
    options: list[str] = list(config.get("options", []))
    explanation = str(config.get("explanation", ""))
    passed = selected_index == correct

    chosen = options[selected_index] if 0 <= selected_index < len(options) else "(no answer)"
    answer = options[correct] if 0 <= correct < len(options) else "(unknown)"
    misconception = ""
    if not passed:
        per_option = config.get("misconception_per_option", {})
        misconception = str(per_option.get(str(selected_index), "concept-confusion"))

    return GradeResult(
        score=1.0 if passed else 0.0,
        status=SubmissionStatus.PASSED if passed else SubmissionStatus.FAILED,
        checks=[
            Check(
                name="Correct answer selected",
                passed=passed,
                message="Correct." if passed else "Not quite.",
                expected=answer,
                actual=chosen,
            )
        ],
        feedback=explanation or ("Correct." if passed else f"The answer is: {answer}"),
        misconceptions=[] if passed else [misconception],
    )


# ---------------------------------------------------------------------------
# AST assertion helpers
# ---------------------------------------------------------------------------

_NODE_LABELS = {
    "ListComp": "a list comprehension",
    "DictComp": "a dict comprehension",
    "SetComp": "a set comprehension",
    "GeneratorExp": "a generator expression",
    "For": "a for loop",
    "While": "a while loop",
    "Try": "a try/except block",
    "With": "a with statement",
    "Lambda": "a lambda",
    "ClassDef": "a class definition",
    "FunctionDef": "a function definition",
    "AsyncFunctionDef": "an async function definition",
    "Yield": "a yield",
    "Assert": "an assert",
    "Global": "a global statement",
    "Nonlocal": "a nonlocal statement",
}


def _find_function(tree: ast.AST, name: str) -> ast.FunctionDef | ast.AsyncFunctionDef | None:
    for node in ast.walk(tree):
        if isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef) and node.name == name:
            return node
    return None


def _evaluate_assertion(tree: ast.AST, source: str, spec: dict[str, Any]) -> Check:
    """Evaluate one structural assertion against the parsed source."""
    kind = str(spec.get("kind", ""))
    label = spec.get("label")

    if kind == "defines_function":
        name = str(spec.get("name", ""))
        node = _find_function(tree, name)
        return Check(
            name=label or f"Defines a function named `{name}`",
            passed=node is not None,
            message="Found." if node else f"No function named `{name}` was defined.",
        )

    if kind == "defines_class":
        name = str(spec.get("name", ""))
        found = any(isinstance(node, ast.ClassDef) and node.name == name for node in ast.walk(tree))
        return Check(
            name=label or f"Defines a class named `{name}`",
            passed=found,
            message="Found." if found else f"No class named `{name}` was defined.",
        )

    if kind in {"uses_construct", "forbids_construct"}:
        node_name = str(spec.get("node", ""))
        node_type = getattr(ast, node_name, None)
        # Only real AST classes are usable with isinstance; an author typo names
        # something that is not a type, and must not crash the grader.
        present = isinstance(node_type, type) and any(
            isinstance(n, node_type) for n in ast.walk(tree)
        )
        described = _NODE_LABELS.get(node_name, node_name)
        if kind == "uses_construct":
            return Check(
                name=label or f"Uses {described}",
                passed=present,
                message="Found." if present else f"Your solution does not use {described}.",
            )
        return Check(
            name=label or f"Avoids {described}",
            passed=not present,
            message=str(spec.get("message", f"Your solution should not use {described}."))
            if present
            else "Good — not used.",
        )

    if kind == "calls_function":
        name = str(spec.get("name", ""))
        called = any(
            isinstance(node, ast.Call)
            and (
                (isinstance(node.func, ast.Name) and node.func.id == name)
                or (isinstance(node.func, ast.Attribute) and node.func.attr == name)
            )
            for node in ast.walk(tree)
        )
        return Check(
            name=label or f"Calls `{name}()`",
            passed=called,
            message="Found." if called else f"`{name}()` is never called.",
        )

    if kind == "imports_module":
        name = str(spec.get("name", ""))
        imported = any(
            (isinstance(node, ast.Import) and any(a.name.split(".")[0] == name for a in node.names))
            or (isinstance(node, ast.ImportFrom) and (node.module or "").split(".")[0] == name)
            for node in ast.walk(tree)
        )
        return Check(
            name=label or f"Imports `{name}`",
            passed=imported,
            message="Found." if imported else f"`{name}` is not imported.",
        )

    if kind == "max_lines":
        limit = int(spec.get("value", 0))
        actual = len([line for line in source.splitlines() if line.strip()])
        return Check(
            name=label or f"At most {limit} lines of code",
            passed=actual <= limit,
            message=f"{actual} non-blank lines.",
            expected=f"<= {limit}",
            actual=str(actual),
        )

    if kind == "has_docstring":
        target_name = spec.get("name")
        if target_name:
            node = _find_function(tree, str(target_name))
            has = node is not None and ast.get_docstring(node) is not None
            return Check(
                name=label or f"`{target_name}` has a docstring",
                passed=has,
                message="Found." if has else "Add a docstring explaining what it does.",
            )
        has = ast.get_docstring(tree) is not None  # type: ignore[arg-type]
        return Check(
            name=label or "Module has a docstring",
            passed=has,
            message="Found." if has else "Add a module-level docstring.",
        )

    if kind == "has_type_hints":
        name = str(spec.get("name", ""))
        node = _find_function(tree, name)
        if node is None:
            return Check(
                name=label or f"`{name}` is annotated",
                passed=False,
                message=f"`{name}` is not defined.",
            )
        annotated = node.returns is not None and all(
            arg.annotation is not None
            for arg in [*node.args.args, *node.args.kwonlyargs]
            if arg.arg not in {"self", "cls"}
        )
        return Check(
            name=label or f"`{name}` has type hints on parameters and return",
            passed=annotated,
            message="Fully annotated." if annotated else "Annotate every parameter and the return.",
        )

    logger.warning("unknown static assertion kind: %s", kind)
    return Check(
        name=label or f"Unknown assertion '{kind}'",
        passed=False,
        message="This exercise is misconfigured; please report it.",
    )


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------


def _timeout_result() -> GradeResult:
    return GradeResult(
        score=0.0,
        status=SubmissionStatus.TIMED_OUT,
        checks=[
            Check(
                name="Program finishes in time", passed=False, message="The run hit the time limit."
            )
        ],
        feedback=(
            "Your program did not finish in time. The usual causes are a loop whose "
            "condition never becomes false, a loop variable that is never updated, or a "
            "recursive call with no base case. Trace the loop: what has to change for it "
            "to stop?"
        ),
        misconceptions=["infinite-loop"],
    )


def _crash_result(result: ExecutionResult) -> GradeResult:
    slug, explanation = interpret_traceback(result.stderr)
    return GradeResult(
        score=0.0,
        status=SubmissionStatus.ERROR,
        checks=[
            Check(
                name="Program runs without crashing",
                passed=False,
                message=f"Exited with code {result.exit_code}.",
                actual=result.stderr.strip()[:4000],
            )
        ],
        feedback=explanation
        or "Your program raised an error. Read the last line of the "
        "traceback first — it names the error type and the reason.",
        misconceptions=[slug] if slug else ["runtime-error"],
    )


def _match_authored_misconceptions(exercise: Exercise, output: str) -> list[str]:
    """Apply author-supplied ``{"pattern", "misconception"}`` rules to the output."""
    found: list[str] = []
    for rule in exercise.misconception_rules:
        pattern = str(rule.get("pattern", ""))
        slug = str(rule.get("misconception", ""))
        if not pattern or not slug:
            continue
        try:
            if re.search(pattern, output, re.IGNORECASE | re.MULTILINE):
                found.append(slug)
        except re.error:
            logger.warning("invalid misconception pattern on %s: %s", exercise.slug, pattern)
    return found


def grade(
    exercise: Exercise,
    *,
    files: dict[str, str],
    result: ExecutionResult | None,
    selected_index: int | None = None,
) -> GradeResult:
    """Dispatch to the grader configured on ``exercise``."""
    grader = GraderKind(exercise.grader)

    if grader is GraderKind.MULTIPLE_CHOICE:
        return grade_multiple_choice(exercise, selected_index if selected_index is not None else -1)
    if grader is GraderKind.STATIC_ASSERT:
        return grade_static_assert(exercise, files)

    if result is None:
        return GradeResult(
            score=0.0,
            status=SubmissionStatus.ERROR,
            checks=[Check(name="Execution", passed=False, message="Code was not executed.")],
            feedback="The execution engine did not return a result. Please try again.",
        )
    if result.error:
        return GradeResult(
            score=0.0,
            status=SubmissionStatus.ERROR,
            checks=[Check(name="Execution", passed=False, message=result.error)],
            feedback="The execution engine is unavailable right now. Your work is saved — "
            "please try again in a moment.",
        )

    if grader is GraderKind.STDOUT_MATCH:
        return grade_stdout_match(exercise, result)
    return grade_pytest(exercise, result)


# --- browser entry point ---------------------------------------------------


def grade_submission(payload: dict) -> str:
    """Grade one submission and return the API's SubmissionResponse fields.

    ``payload`` carries the exercise document exported by
    ``tools/export_static.py``, the learner's files, and — for graders that need
    the program to have run — the result Pyodide produced.
    """
    import json

    exercise = Exercise(payload["exercise"])
    execution = None
    if payload.get("execution") is not None:
        raw = payload["execution"]
        execution = ExecutionResult(
            ok=raw.get("exit_code") == 0,
            exit_code=int(raw.get("exit_code", 1)),
            stdout=raw.get("stdout", ""),
            stderr=raw.get("stderr", ""),
            timed_out=bool(raw.get("timed_out")),
            duration_ms=int(raw.get("duration_ms", 0)),
            error=raw.get("error"),
        )

    result = grade(
        exercise,
        files=payload.get("files") or {},
        result=execution,
        selected_index=payload.get("selected_index"),
    )
    return json.dumps(
        {
            "status": result.status.value,
            "score": result.score,
            "checks": [check.to_dict() for check in result.checks],
            "feedback": result.feedback,
            "misconceptions": result.misconceptions,
        }
    )
