"""Initial schema.

Revision ID: 0001_initial
Revises:
Created: 2026-09-06

This baseline revision builds the schema from the SQLAlchemy metadata rather
than from a long hand-written list of ``op.create_table`` calls.

Why: on a greenfield project the models *are* the specification, and a
transcribed copy of them can drift from the source of truth without anyone
noticing. Generating the baseline from metadata makes drift impossible for
revision one.

Every subsequent migration is a normal autogenerated diff
(``alembic revision --autogenerate -m "..."``), which compares the live schema
against the same metadata — so this shortcut applies only to the baseline and
does not weaken the migration history that follows it. See
``docs/DEPLOYMENT.md``.
"""

from __future__ import annotations

from collections.abc import Sequence

import app.models  # noqa: F401  - registers every mapper on Base.metadata
from alembic import op
from app.db.base import Base

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create every table defined by the ORM metadata."""
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    """Drop every table. Destructive, and only meaningful for the baseline."""
    Base.metadata.drop_all(bind=op.get_bind())
