#!/usr/bin/env python
"""Pre-render the API's read responses to static JSON for GitHub Pages.

With no accounts there are no per-user reads, so every GET this application
serves is a pure function of the seed curriculum. That makes them exportable:
this script seeds a throwaway database, drives the *real* FastAPI app through
``TestClient``, and writes each response to a file the browser can fetch
directly. The frontend's static mode then reads these instead of a network API.

Going through the app rather than the ORM matters — the response shapes stay
byte-identical to what the API-backed mode returns, so one set of TypeScript
types describes both and neither can drift.

Two things need more than the API gives:

* **Gated content.** Hints, reference solutions and hidden test files are served
  only by their own gated endpoints, because on a real deployment a learner must
  earn them. In the browser there is no server left to enforce that, so they
  have to ship. The client still gates them in the UI, which is now a courtesy
  rather than a control — see docs/DEPLOY_GITHUB_PAGES.md.
* **Search.** It takes a query, so instead of enumerating queries we export a
  flat index and rank client-side.

Usage::

    python tools/export_static.py [--out frontend/public/content]
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
import tempfile
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parents[1]
BACKEND = REPO / "backend"

# Configure before app.core.config is imported, since settings are cached.
# `client` executor is what makes the API populate `execution_plan` — the recipe
# (and hidden tests) the browser needs in order to run an exercise at all.
os.environ.update(
    {
        "PYFORGE_ENV": "development",
        "PYFORGE_DEBUG": "false",
        "PYFORGE_LOG_LEVEL": "WARNING",
        "PYFORGE_SECRET_KEY": "static-export-only-key-not-used-at-runtime-0123456789",
        "PYFORGE_EXECUTOR": "client",
        "PYFORGE_REDIS_URL": "",
        "PYFORGE_ANTHROPIC_API_KEY": "",
        "PYFORGE_FIREBASE_PROJECT_ID": "",
    }
)

sys.path.insert(0, str(BACKEND))


def _log(message: str) -> None:
    print(f"  {message}", flush=True)


#: Stands in for the four ``app.*`` names grading.py imports. Each is reduced to
#: exactly the surface grading.py actually touches — anything more would be
#: pretending the browser has a server in it.
_GRADER_SHIM = '''"""Generated by tools/export_static.py — do not edit.

The grading module from the PyForge backend, shipped verbatim so that the
browser grades submissions with the same code the server would. Only its
application imports are replaced, by the shims below.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum


class _NullLogger:
    """grading.py logs author mistakes; in a browser there is nowhere to log."""

    def warning(self, *args: object, **kwargs: object) -> None:
        pass

    def info(self, *args: object, **kwargs: object) -> None:
        pass


def get_logger(_name: str) -> _NullLogger:
    return _NullLogger()


class GraderKind(StrEnum):
    STDOUT_MATCH = "stdout_match"
    PYTEST = "pytest"
    STATIC_ASSERT = "static_assert"
    MULTIPLE_CHOICE = "multiple_choice"


class SubmissionStatus(StrEnum):
    PASSED = "passed"
    FAILED = "failed"
    PARTIAL = "partial"
    ERROR = "error"
    TIMED_OUT = "timed_out"


@dataclass(frozen=True)
class ExecutionResult:
    """The subset of the server's ExecutionResult that grading reads."""

    ok: bool = False
    exit_code: int = 1
    stdout: str = ""
    stderr: str = ""
    timed_out: bool = False
    duration_ms: int = 0
    error: str | None = None


class Exercise:
    """A stand-in for the ORM row.

    ``grading.py`` only reads attributes off it, and every annotation in that
    module is a string (``from __future__ import annotations``), so nothing ever
    checks this type.
    """

    def __init__(self, data: dict) -> None:
        self.slug = data.get("slug", "")
        self.grader = data.get("grader", "")
        self.grader_config = data.get("grader_config") or {}
        self.misconception_rules = data.get("misconception_rules") or []


'''

#: The bridge the worker calls. Kept separate from the vendored source so the
#: generated file reads as "their code, then our entry point".
_GRADER_ENTRYPOINT = '''

# --- browser entry point ---------------------------------------------------


def grade_submission(payload: dict) -> str:
    """Grade one submission and return the API's SubmissionResponse fields.

    ``payload`` carries the exercise document exported by
    ``tools/export_static.py``, the learner's files, and — for graders that need
    the program to have run — the result Pyodide produced.
    """
    import json

    exercise = Exercise(payload["exercise"])
    execution = None
    if payload.get("execution") is not None:
        raw = payload["execution"]
        execution = ExecutionResult(
            ok=raw.get("exit_code") == 0,
            exit_code=int(raw.get("exit_code", 1)),
            stdout=raw.get("stdout", ""),
            stderr=raw.get("stderr", ""),
            timed_out=bool(raw.get("timed_out")),
            duration_ms=int(raw.get("duration_ms", 0)),
            error=raw.get("error"),
        )

    result = grade(
        exercise,
        files=payload.get("files") or {},
        result=execution,
        selected_index=payload.get("selected_index"),
    )
    return json.dumps(
        {
            "status": result.status.value,
            "score": result.score,
            "checks": [check.to_dict() for check in result.checks],
            "feedback": result.feedback,
            "misconceptions": result.misconceptions,
        }
    )
'''


#: The reviewer needs no shim — only an entry point, because ``review_files``
#: already returns exactly the API's ReviewResponse via ``to_dict``.
_REVIEWER_ENTRYPOINT = '''

# --- browser entry point ---------------------------------------------------


def review_submission(files: dict) -> str:
    """Review the supplied files and return the API's ReviewResponse fields."""
    import json

    return json.dumps(review_files(files).to_dict())
'''


#: Lists whose order carries no meaning, and which the database returns in an
#: arbitrary order. They are sorted so two exports of the same curriculum are
#: byte-identical — which is what lets CI diff a committed tree against a fresh
#: export. Ordered lists (modules, lessons, hints, rubric rows, multiple-choice
#: options) are deliberately absent: reordering those would change the content.
UNORDERED_LIST_KEYS = frozenset(
    {
        "concepts",
        "concept_slugs",
        "prerequisites",
        "prerequisite_slugs",
        "blocked_by",
        "misconceptions",
        "tracks",
    }
)

#: Timestamps that record when the *export ran*, not anything about the content.
#: Left in place they would change on every run. Nothing in the static build has
#: real user data, so none of these carries information.
VOLATILE_TIMESTAMP_KEYS = frozenset(
    {"updated_at", "created_at", "last_login_at", "awarded_at", "last_practiced_at"}
)

#: What a normalised timestamp becomes. A fixed instant rather than null, because
#: some of these fields are non-nullable in the API contract.
EPOCH = "1970-01-01T00:00:00"


def _sort_key(item: Any) -> str:
    """Order list members stably, whether they are strings or documents."""
    if isinstance(item, dict):
        for field in ("slug", "key", "id", "name", "concept_slug"):
            if field in item:
                return str(item[field])
        return json.dumps(item, sort_keys=True)
    return str(item)


def normalise(value: Any, key: str | None = None) -> Any:
    """Make a response document byte-stable across export runs.

    Two runs against the same curriculum must produce identical bytes, otherwise
    the CI check that compares the committed tree with a fresh export fails on
    every push and stops meaning anything.
    """
    if isinstance(value, dict):
        return {k: normalise(v, k) for k, v in value.items()}
    if isinstance(value, list):
        items = [normalise(item) for item in value]
        return sorted(items, key=_sort_key) if key in UNORDERED_LIST_KEYS else items
    if key in VOLATILE_TIMESTAMP_KEYS and isinstance(value, str) and value:
        return EPOCH
    return value


class Exporter:
    """Drives the app and writes the JSON tree."""

    def __init__(self, out: Path) -> None:
        self.out = out
        self.written = 0
        self.bytes = 0

    # -- plumbing ----------------------------------------------------------

    def write(self, relative: str, payload: Any) -> None:
        """Write one JSON document, creating parent directories as needed."""
        target = self.out / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        # separators drop the spaces json.dumps adds by default; on ~1500 files
        # that is a worthwhile chunk of transfer for output nobody reads by hand.
        # `normalise` makes the bytes reproducible; see its docstring.
        text = json.dumps(normalise(payload), separators=(",", ":"), ensure_ascii=False)
        target.write_text(text, encoding="utf-8")
        self.written += 1
        self.bytes += len(text.encode("utf-8"))

    def get(self, path: str, **params: Any) -> Any:
        """GET an endpoint as the throwaway learner, asserting success."""
        response = self.client.get(path, headers=self.headers, params=params or None)
        if response.status_code != 200:
            raise RuntimeError(
                f"GET {path} -> {response.status_code}: {response.text[:300]}"
            )
        return response.json()

    #: The pagination ceiling every listing endpoint shares (``deps.Pagination``).
    PAGE = 200

    def get_all(self, path: str, **params: Any) -> list[Any]:
        """Page through a listing endpoint until it stops returning rows.

        Listings cap ``limit`` at 200, so anything larger has to be walked. This
        also means the export does not silently truncate when the curriculum
        grows past whatever limit happened to be hard-coded.
        """
        rows: list[Any] = []
        offset = 0
        while True:
            page = self.get(path, limit=self.PAGE, offset=offset, **params)
            rows.extend(page)
            if len(page) < self.PAGE:
                return rows
            offset += self.PAGE

    # -- lifecycle ---------------------------------------------------------

    def setup(self) -> None:
        """Seed a temporary database and open a client against it."""
        from app.db.base import Base
        from app.db.init_db import seed_all
        from app.db.session import get_engine, get_session_factory, reset_engine
        from app.main import create_app
        from app.services.auth import AuthService
        from fastapi.testclient import TestClient

        self.tmp = Path(tempfile.mkdtemp(prefix="pyforge-export-"))
        os.environ["PYFORGE_DATABASE_URL"] = (
            f"sqlite+pysqlite:///{self.tmp / 'export.db'}"
        )

        from app.core.config import get_settings

        get_settings.cache_clear()
        reset_engine()
        Base.metadata.create_all(bind=get_engine())

        self.session = get_session_factory()()
        _log("seeding curriculum")
        seed_all(self.session)

        # A throwaway account, purely so authenticated endpoints answer. Its
        # progress is all zeros, which is exactly a first-time visitor's state.
        learner = AuthService(self.session).register(
            email="static-export@localhost",
            password="static-export-password-not-a-secret-1",
            display_name="Learner",
        )
        self.session.commit()
        self.user = learner
        self.headers = {
            "Authorization": f"Bearer {AuthService.issue_tokens(learner).access_token}"
        }

        app = create_app()

        def _override():  # type: ignore[no-untyped-def]
            yield self.session

        from app.db.session import get_db

        app.dependency_overrides[get_db] = _override
        self.client = TestClient(app)

    def teardown(self) -> None:
        """Close the session and remove the temporary database."""
        self.session.close()
        shutil.rmtree(self.tmp, ignore_errors=True)

    # -- exports -----------------------------------------------------------

    def export_courses(self) -> list[str]:
        """Course list and each course's tree. Returns lesson slugs."""
        courses = self.get("/api/courses")
        self.write("courses.json", courses)

        lesson_slugs: list[str] = []
        for summary in courses:
            slug = summary["slug"]
            detail = self.get(f"/api/courses/{slug}")
            self.write(f"courses/{slug}.json", detail)
            for module in detail.get("modules", []):
                for lesson in module.get("lessons", []):
                    lesson_slugs.append(lesson["slug"])
        _log(f"{len(courses)} courses, {len(lesson_slugs)} lessons")
        return lesson_slugs

    def export_lessons(self, slugs: list[str]) -> list[str]:
        """Each lesson. Returns every exercise slug they reference."""
        exercise_slugs: list[str] = []
        for slug in slugs:
            detail = self.get(f"/api/lessons/{slug}")
            self.write(f"lessons/{slug}.json", detail)
            for exercise in detail.get("exercises", []):
                exercise_slugs.append(exercise["slug"])
        return exercise_slugs

    def export_exercises(self, slugs: list[str]) -> None:
        """Each exercise, with the gated content the browser cannot request."""
        from app.models import Exercise
        from sqlalchemy import select

        catalogue = self.get_all("/api/exercises")
        self.write("exercises.json", catalogue)
        challenges = self.get_all("/api/challenges")
        self.write("challenges.json", challenges)

        every = {slug for slug in slugs}
        every.update(item["slug"] for item in catalogue)
        every.update(item["slug"] for item in challenges)

        for slug in sorted(every):
            detail = self.get(f"/api/exercises/{slug}")
            row = self.session.scalar(select(Exercise).where(Exercise.slug == slug))
            if row is None:
                continue
            # The gated extras. The UI still makes a learner work through the
            # hint ladder before showing these; it just cannot enforce it.
            detail["hints"] = [
                {
                    "level": hint.level,
                    "text": hint.text,
                    "penalty": hint.penalty,
                    "is_last": hint.level >= len(row.hints),
                }
                for hint in sorted(row.hints, key=lambda h: h.level)
            ]
            detail["solution"] = {
                "files": row.solution_files,
                "explanation": row.solution_explanation,
            }
            detail["misconception_rules"] = row.misconception_rules
            # grader_config drives client-side grading: expected stdout, the AST
            # assertions, the correct multiple-choice index.
            detail["grader_config"] = row.grader_config
            self.write(f"exercises/{slug}.json", detail)
        _log(f"{len(every)} exercises (with hints, solutions and graders)")

    def export_reference(self) -> None:
        """The reference library."""
        entries = self.get_all("/api/reference")
        self.write("reference.json", entries)
        for entry in entries:
            key = entry["key"]
            # Keys contain dots but never slashes, so they are safe as filenames.
            self.write(f"reference/{key}.json", self.get(f"/api/reference/{key}"))
        _log(f"{len(entries)} reference entries")

    def export_projects(self) -> None:
        """Project briefs and their starter workspaces."""
        projects = self.get("/api/projects")
        self.write("projects.json", projects)
        for summary in projects:
            slug = summary["slug"]
            self.write(f"projects/{slug}.json", self.get(f"/api/projects/{slug}"))
        _log(f"{len(projects)} projects")

    def export_concepts(self) -> None:
        """The concept graph, which mastery and prerequisites hang off."""
        concepts = self.get("/api/concepts")
        self.write("concepts.json", concepts)
        _log(f"{len(concepts)} concepts")

    def export_interview(self) -> None:
        """Interview questions, with the answers the client needs to mark them.

        Read straight from the ORM rather than through ``/api/interview/questions``:
        that endpoint deliberately withholds ``correct_index`` and ``explanation``
        (the client is meant to POST an answer to have it marked), caps at 100 and
        offers no offset. In the browser there is nothing left to POST to, so the
        answers have to travel with the questions.
        """
        from app.models import QuizQuestion
        from sqlalchemy import select

        rows = self.session.scalars(
            select(QuizQuestion).order_by(QuizQuestion.slug)
        ).all()
        questions = [
            {
                "slug": row.slug,
                "question": row.question,
                "code_snippet": row.code_snippet,
                "options": row.options,
                "category": row.category,
                "level": row.level,
                "tracks": row.tracks,
                "concept_slugs": row.concept_slugs,
                "correct_index": row.correct_index,
                "explanation": row.explanation,
            }
            for row in rows
        ]
        self.write("interview.json", questions)
        _log(f"{len(questions)} interview questions")

    def export_search_index(self) -> None:
        """A flat index, since search takes a query and is ranked client-side."""
        index: list[dict[str, Any]] = []

        for course in self.get("/api/courses"):
            detail = self.get(f"/api/courses/{course['slug']}")
            for module in detail.get("modules", []):
                for lesson in module.get("lessons", []):
                    index.append(
                        {
                            "kind": "lesson",
                            "slug": lesson["slug"],
                            "title": lesson["title"],
                            "snippet": lesson.get("summary", ""),
                            "url": f"/learn/{lesson['slug']}",
                        }
                    )
        for exercise in self.get_all("/api/exercises"):
            index.append(
                {
                    "kind": "exercise",
                    "slug": exercise["slug"],
                    "title": exercise["title"],
                    "snippet": f"{exercise['kind']} · {exercise['level']}",
                    "url": f"/practice/{exercise['slug']}",
                }
            )
        for entry in self.get_all("/api/reference"):
            index.append(
                {
                    "kind": "reference",
                    "slug": entry["key"],
                    "title": entry["title"],
                    "snippet": entry.get("summary", ""),
                    "url": f"/reference/{entry['key']}",
                }
            )
        for project in self.get("/api/projects"):
            index.append(
                {
                    "kind": "project",
                    "slug": project["slug"],
                    "title": project["title"],
                    "snippet": project.get("summary", ""),
                    "url": f"/projects/{project['slug']}",
                }
            )
        for concept in self.get("/api/concepts"):
            index.append(
                {
                    "kind": "concept",
                    "slug": concept["slug"],
                    "title": concept["name"],
                    "snippet": concept.get("summary", "")
                    or concept.get("description", ""),
                    "url": "/progress",
                }
            )

        self.write("search-index.json", index)
        _log(f"{len(index)} search entries")

    def export_grader(self) -> None:
        """Vendor the real grading module for Pyodide to run.

        Grading must happen client-side, and reimplementing it in TypeScript
        would fork logic that decides whether a learner passed — including the
        AST assertions, which need Python's own ``ast`` module anyway. So instead
        the actual ``app/services/grading.py`` is shipped verbatim, with its four
        ``app.*`` imports replaced by shims.

        That keeps one implementation of grading. ``tests/test_static_grader.py``
        runs the generated module against the real one to prove they agree.
        """
        source = (BACKEND / "app" / "services" / "grading.py").read_text(
            encoding="utf-8"
        )

        # Drop the imports that reach into the application package. Everything
        # else grading.py uses is standard library.
        for line in (
            "from app.core.logging import get_logger\n",
            "from app.execution.base import ExecutionResult\n",
            "from app.models import Exercise\n",
            "from app.models.enums import GraderKind, SubmissionStatus\n",
        ):
            if line not in source:
                raise RuntimeError(
                    f"grading.py no longer imports {line.strip()!r}; update the shim in "
                    "tools/export_static.py so the vendored grader still builds."
                )
            source = source.replace(line, "")

        # The shim already opens with a future import, and Python allows only one
        # and only at the top of the file.
        source = source.replace("from __future__ import annotations\n", "", 1)

        self.out.mkdir(parents=True, exist_ok=True)
        (self.out / "grader.py").write_text(
            _GRADER_SHIM + source + _GRADER_ENTRYPOINT, "utf-8"
        )
        self.written += 1
        _log("vendored grading.py for the browser")

    def export_reviewer(self) -> None:
        """Vendor the code-review engine, which needs no shimming at all.

        ``app/services/code_review.py`` imports only ``ast``, ``re``,
        ``dataclasses``, ``enum`` and ``typing``, so the whole senior-engineer
        review runs in Pyodide unmodified — the feature survives having no server
        for the cost of copying a file.
        """
        source = (BACKEND / "app" / "services" / "code_review.py").read_text(
            encoding="utf-8"
        )
        if "from app." in source or "\nimport app" in source:
            raise RuntimeError(
                "code_review.py has grown an application import, so it can no longer be "
                "vendored unmodified. Add a shim in tools/export_static.py."
            )

        (self.out / "reviewer.py").write_text(source + _REVIEWER_ENTRYPOINT, "utf-8")
        self.written += 1
        _log("vendored code_review.py for the browser")

    def export_manifest(self) -> None:
        """A marker the client checks so a stale deploy fails loudly."""
        self.write(
            "manifest.json",
            {
                "format": 1,
                "files": self.written,
                "generated_by": "tools/export_static.py",
            },
        )


def main() -> int:
    """Export the content tree."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        type=Path,
        default=REPO / "frontend" / "public" / "content",
        help="destination directory (wiped before writing)",
    )
    args = parser.parse_args()

    out: Path = args.out
    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True)

    print(f"Exporting static content -> {out}")
    exporter = Exporter(out)
    exporter.setup()
    try:
        lesson_slugs = exporter.export_courses()
        exercise_slugs = exporter.export_lessons(lesson_slugs)
        exporter.export_exercises(exercise_slugs)
        exporter.export_reference()
        exporter.export_projects()
        exporter.export_concepts()
        exporter.export_interview()
        exporter.export_search_index()
        exporter.export_grader()
        exporter.export_reviewer()
        exporter.export_manifest()
    finally:
        exporter.teardown()

    print(f"\n{exporter.written} files, {exporter.bytes / 1024:.0f} KiB")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
